### ISSUE TITLE
Category text dark in night mode

### ISSUE THREAD

**Issue by hafarooki** [B-iggy/discourse-dark-theme#1]
When switched to night mode, category text remains dark
![image](https://user-images.githubusercontent.com/6323125/45095031-00ade680-b0eb-11e8-80f6-21154e2c0a93.png)

**Comment by B-iggy** [comment]
Sorry for the late reply! I will check and update the theme in general. I found myself areas to improve :)

**Comment by B-iggy** [comment]
SORRY for the delay *shame*

But I finally reworked the whole theme!
Please let me know if there are still contrast issues!

**Comment by hafarooki** [comment]
Thanks, it's a lot nicer now

**Comment by hafarooki** [comment]
Here's another contrast issue:
![image](https://user-images.githubusercontent.com/6323125/56071111-20c91680-5d5a-11e9-8c50-cf109f88dd4b.png)

**Comment by hafarooki** [comment]
![image](https://user-images.githubusercontent.com/6323125/56071119-32aab980-5d5a-11e9-98e6-276f40179639.png)
This could also still be a bit brighter

**Comment by B-iggy** [comment]
Hey @MicleBrick 
thanks for the report.
I searched a bit and couldn't find the page with such a contrast.
Can you please let me know on what page this contrast is available?
like ...url.../top for example?
